server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: userManagementService
          uri: http://localhost:8010/
          predicates:
          - Path=/api/firstModule/userService/**
          - Method=GET,POST
        - id: doctor-logic
          uri: http://localhost:8020/
          predicates:
          - Path=/api/secondModule/appointment/**
          - Method=GET,POST

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
  application:
    name: gateway-api-service


